### ISSUE TITLE
Remove console log

### ISSUE THREAD

**Issue by ramirez** [traverson/halfred#20]
Hi, 

I'm using traverson with traverson-hal which uses halfred under the hood. My problem is that halfred sends a lot of debugging log the console and there is no way to turn it off. I created an issue for this request in the traverson-hal repo as well: (https://github.com/traverson/traverson-hal/issues/30).

Cheers,

LEo

**Comment by basti1302** [comment]
A fixed has landed in traverson-hal 6.0.3
