### ISSUE TITLE
How to play Resource with data class in Typescript

### ISSUE THREAD

**Issue by yejianfengblue** [traverson/halfred#50]
May I ask question in Github issues? Because I find the tag `traverson` doesn't exist in stackoverflow. And no much resource can be googled with keyword "traverson hal typescript".

This is the response body in hal json returned from Spring Data REST backend. There is a root level property `page` besides `_embedded` and `_links`.
```json
{
  "_embedded" : {
    "users" : [ {
      "username" : "apple",
      "lastLoginTime" : "2021-09-22T13:32:55.76",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/users/60857057c116924b2a7affc8"
        },
        "user" : {
          "href" : "http://localhost:8080/users/60857057c116924b2a7affc8"
        }
      }
    }, {
      "username" : "banana",
      "lastLoginTime" : "2021-09-22T13:43:51.145",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/users/6085726fc116924b2a7affc9"
        },
        "user" : {
          "href" : "http://localhost:8080/users/6085726fc116924b2a7affc9"
        }
      }
    } ]
  },
  "_links" : {
    "first" : {
      "href" : "http://localhost:8080/users?page=0&size=2"
    },
    "self" : {
      "href" : "http://localhost:8080/users?page=0&size=2"
    },
    "next" : {
      "href" : "http://localhost:8080/users?page=1&size=2"
    },
    "last" : {
      "href" : "http://localhost:8080/users?page=86&size=2"
    },
    "profile" : {
      "href" : "http://localhost:8080/profile/users"
    },
    "search" : {
      "href" : "http://localhost:8080/users/search"
    }
  },
  "page" : {
    "size" : 2,
    "totalElements" : 173,
    "totalPages" : 87,
    "number" : 0
  }
}
```
Traverson code.
```typescript
traverson
  .from('http://localhost:8080/users')
  .jsonHal()
  .getResource((error, doc) => {
    if (error) {
      console.error(error);
    } else {
      let resource = halfred.parse(doc);  // type of halfred.Resource
      console.info('resource=', resource);
      console.info('page=', resource.page);  // error Property 'page' does not exist on type 'Resource'
      let users = resource.embeddedArray('users');  // type of Resource[]
      let user0 = users[0];  // type of halfred.Resource
      console.info('user0.username=', user0.username);  // error Property 'username' does not exist on type 'Resource'
    }
  });
```
data class
``` typescript
// User.ts
export default class User {
  constructor(readonly username: string, readonly lastLoginTime: date);
}
```
Question 1  
`resource.embeddedArray('users')` returns an array of `Resource`. Should I convert to a data class `User` or keep using the type [`Resource`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/halfred/index.d.ts)? How to convert `Resource` to class `User` in Typescript?

Question 2
If I keep using the type `Resource` and access some data such as username, even though the username value is logged to console, I get IDE error "Property 'username' does not exist on type 'Resource'".  Can anyone give me some advice?

It would be great if some traverson hal typescript example can be provided.

**Comment by basti1302** [comment]
The type definitions that Traverson provides can only reason about the concepts it works with. You use traverson to fetch resources. Traverson has no knowledge about the underlying concepts that your remote API uses. It can not know anything about _users_ etc. Thus, Traverson can also not help with converting resources to your individual types (users). You need to do a type conversion from `Resource` to `User` for `user0` before accessing properties that are defined for the type `User`.

How to do this is more of a TypeScript problem, and not so much a problem of using Traverson. You would encounter the same problem, no matter how you load data from your Spring Data back end, even without using Traverson.

There seem to be multiple ways to solve this, I would recommend searching for "how do I cast a JSON object to a TypeScript class" or similar search terms.

Here are a few links that might be helpful:
* https://stackoverflow.com/questions/40421100/how-to-parse-a-json-object-to-a-typescript-object
* https://trungk18.com/experience/cast-parse-json-object-to-typescript-class/
* https://github.com/typestack/class-transformer might be useful

I hope that helps, kind regards

  Bastian

**Comment by yejianfengblue** [comment]
Thank you for the explanation and suggestion. I ask this wrong question because I see some axios code `axios.get<User[]>`.
```javascript
interface User {
    id: number;
    firstName: string;
}

axios.get<User[]>('http://localhost:8080/admin/users')
        .then(response => {
            console.log(response.data);
            setUserList( response.data );
        });
```
